#!/usr/bin/env python3
import os
import re
import json

ROOT = "Academia Arcana Victory"
OUT_DIR = ".pareceres"
OUT_MD = os.path.join(OUT_DIR, "collected_editor_notes.md")
OUT_JSON = os.path.join(OUT_DIR, "collected_editor_notes.json")

NAME_QUOTE_RE = re.compile(r'^(?P<name>[A-ZÁÉÍÓÚÀÈÌÒÙÇ][A-Za-zÁÉÍÓÚÀÈÌÒÙÇãõÃÕáéíóúâêîôûäëïöüç\-\s]{1,80}):\s*"(?P<quote>.*?)"', re.M)
NAME_QUOTE_RE_SQ = re.compile(r"^(?P<name>[A-ZÁÉÍÓÚÀÈÌÒÙÇ][A-Za-zÁÉÍÓÚÀÈÌÒÙÇãõÃÕáéíóúâêîôûäëïöüç\-\s]{1,80}):\s*'(?P<quote>.*?)'", re.M)
HTML_COMMENT_RE = re.compile(r'<!--\s*(?P<comment>.*?)\s*-->', re.S)
BRACKET_REF_RE = re.compile(r'^\[//\]: # \((?P<comment>.*?)\)', re.M)

EDITORIAL_KEYWORDS = ['estrutura','ritmo','módulo','arco','escrito','costura','produto','PJs','personagens','mestre','IA','inteligência','satisfatória','continu','cort']
TIP_KEYWORDS = ['jogador','leitor','use','dica','quando','como','recomendo','sugest']

def classify(text):
    t = text.lower()
    for k in EDITORIAL_KEYWORDS:
        if k in t:
            return 'editorial'
    for k in TIP_KEYWORDS:
        if k in t:
            return 'tip'
    return 'unknown'

def scan_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        s = f.read()
    hits = []
    for m in NAME_QUOTE_RE.finditer(s):
        start = s.count('\n', 0, m.start()) + 1
        q = m.group('quote').strip()
        name = m.group('name').strip()
        hits.append({'type':'name_quote','name':name,'text':q,'line':start})
    for m in NAME_QUOTE_RE_SQ.finditer(s):
        start = s.count('\n', 0, m.start()) + 1
        q = m.group('quote').strip()
        name = m.group('name').strip()
        hits.append({'type':'name_quote','name':name,'text':q,'line':start})
    for m in HTML_COMMENT_RE.finditer(s):
        start = s.count('\n', 0, m.start()) + 1
        c = m.group('comment').strip()
        hits.append({'type':'html_comment','text':c,'line':start})
    for m in BRACKET_REF_RE.finditer(s):
        start = s.count('\n', 0, m.start()) + 1
        c = m.group('comment').strip()
        hits.append({'type':'bracket_ref','text':c,'line':start})
    return hits

def main():
    results = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        for fn in filenames:
            if not fn.lower().endswith('.md'):
                continue
            fp = os.path.join(dirpath, fn)
            rel = os.path.relpath(fp)
            hits = scan_file(fp)
            for h in hits:
                h['file'] = rel
                if 'text' in h:
                    h['class'] = classify(h['text'])
                elif 'quote' in h:
                    h['class'] = classify(h['quote'])
                else:
                    h['class'] = 'unknown'
                results.append(h)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_JSON, 'w', encoding='utf-8') as fj:
        json.dump(results, fj, ensure_ascii=False, indent=2)

    with open(OUT_MD, 'w', encoding='utf-8') as fo:
        fo.write('# Collected editor notes\n\n')
        fo.write('This file was generated by scripts/extract_editor_notes.py\n\n')
        for i, r in enumerate(results, 1):
            fo.write(f'## {i} — {r.get("file")} (line {r.get("line")})\n')
            if r.get('type') == 'name_quote':
                fo.write(f'- **source**: name_quote — {r.get("name")}\n')
            else:
                fo.write(f'- **source**: {r.get("type")}\n')
            fo.write(f'- **class (heuristic)**: {r.get("class")}\n')
            fo.write('\n')
            fo.write('```\n')
            fo.write(r.get('text') or r.get('quote') or '')
            fo.write('\n```\n\n')

    print('Wrote', OUT_MD, 'and', OUT_JSON)

if __name__ == '__main__':
    main()
